service: passwordless-example

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  logs:
    restApi: true
  logRetentionInDays: 3

functions:
  createAuthChallenge:
    handler: api/createAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: passwordless-example
          trigger: CreateAuthChallenge
          existing: true
  defineAuthChallenge:
    handler: api/defineAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: passwordless-example
          trigger: DefineAuthChallenge
          existing: true
  verifyAuthChallenge:
    handler: api/verifyAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: passwordless-example
          trigger: VerifyAuthChallengeResponse
          existing: true

resources:
  - ${file(./infra/user-stack.yaml)}
