Resources:
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      # DeviceConfiguration:
      #   ChallengeRequiredOnNewDevice: Boolean
      #   DeviceOnlyRememberedOnUserPrompt: Boolean
      EmailVerificationMessage: Your verification code is {####}.
      EmailVerificationSubject: Your verification code
      UserPoolName: passwordless-example

      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          StringAttributeConstraints:
            MaxLength: 1000
            MinLength: 0
          Required: false
        - AttributeDataType: Number
          Mutable: true
          Name: confirmed
          NumberAttributeConstraints:
            MaxValue: 1
            MinValue: 0
          Required: false
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: passwordless-example
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      # GenerateSecret: Boolean
      # ReadAttributes:
      #  - String
      RefreshTokenValidity: 30
      UserPoolId: !Ref UserPool
      # WriteAttributes:
      #   - String

  #IdentityPool:
  #  Type: "AWS::Cognito::IdentityPool"
  #  Properties:
  #    IdentityPoolName: !Join ["", !Split [".", !Ref Domain]]
  #    AllowUnauthenticatedIdentities: false
  #    # SupportedLoginProviders:
  #    #  String: String
  #    CognitoIdentityProviders:
  #      - ClientId: !Ref UserPoolClient
  #        ProviderName: !GetAtt UserPool.ProviderName
  #        # ServerSideTokenCheck: Boolean